SELECT TOP (1000) [TaskId]
      ,[Subject]
      ,[DateDue]
      ,[CustomerId]
      ,[StatusId]
      ,[AssignType]
      ,[OwnerUserId]
      ,[Note]
      ,[DateCreated]
      ,[CreatedByUserId]
      ,[DateModified]
      ,[ModifiedByUserId]
      ,[RefId]
      ,[RefType]
      ,[IsActive]
      ,[DealId]
  FROM [Venio2].[dbo].[ReminderTasks] as rt where rt.TaskId = 10847